const AuthActionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOAD_USER: "LOAD_USER",
  FORGOT_PWD_SUCCESS: "FORGOT_PWD_SUCCESS",
  FORGOT_PWD_FAIL: "FORGOT_PWD_FAIL",
  AUTH_ERROR: "AUTH_ERROR",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL"
};

export default AuthActionTypes;
