const ShopActionTypes = {
  FETCH_START: "FETCH_START",

  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAIL: "FETCH_CATEGORIES_FAIL",

  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAIL: "UPDATE_CATEGORIES_FAIL",

  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAIL: "DELETE_CATEGORIES_FAIL",

  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAIL: "FETCH_PRODUCTS_FAIL",

  UPDATE_PRODUCTS_SUCCESS: "UPDATE_PRODUCTS_SUCCESS",
  UPDATE_PRODUCTS_FAIL: "UPDATE_PRODUCTS_FAIL",

  DELETE_PRODUCTS_SUCCESS: "DELETE_PRODUCTS_SUCCESS",
  DELETE_PRODUCTS_FAIL: "DELETE_PRODUCTS_FAIL",

  ADD_PRODUCT_PHOTO_SUCCESS: "ADD_PRODUCT_PHOTO_SUCCESS",
  ADD_PRODUCT_PHOTO_FAIL: "ADD_PRODUCT_PHOTO_FAIL",
};

export default ShopActionTypes;
