const CartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  MODIFY_ITEM: "MODIFY_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM",
  CLEAR_CART: "CLEAR_CART",
  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  CART_ERROR: "CART_ERROR"
};

export default CartActionTypes;
